# Generated by Django 3.0.3 on 2021-07-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('calorie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'FoodItems',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PreviousRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('totalCalories', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goal_set', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SetGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
