# Generated by Django 3.0.3 on 2021-07-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myplate_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previousrecords',
            name='date',
        ),
    ]
