# Generated by Django 3.0.3 on 2021-07-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplate_app', '0002_remove_previousrecords_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousrecords',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
